### PR TITLE
Import boost v1.70.0

### PR DESCRIPTION
**Pull request by davidrohr**
@ktf @sawenzel : Not sure how you imported it before.
I just cloned boost 1.70 recursively, and added everything as a single commit to the alisw fork.
Builds for me locally. If this is not how it's supposed to be, someone else will have to have a look.

### CODE REVIEW

**Comment by ktf** [comment]
Did you remove the deleted files?

**Comment by davidrohr** [comment]
yes, wiped everything and copied over the recursive checkout (I hope)

**Comment by sawenzel** [comment]
No idea how this was done before. Just realized that there is a pending PR #2 with the same intention (but different number of files and lines changed).

**Comment by davidrohr** [comment]
hm, good question, no idea what @dennisklein did.

**Comment by dennisklein** [comment]
I deleted everything, unpacked the tarball and committed. Unpacking over the existing files I found too risky (Unpacking will not remove any obsolete files e.g.)

**Comment by davidrohr** [comment]
OK, so @dennisklein used the tarball while I checked out git. If the tarball is smaller, I would go with that one (if it works).

**Comment by dennisklein** [comment]
worked for me a while ago on Fedora 30, was pointing the boost alidist recipe to ~this PR branch~ my branch in #2

**Comment by dennisklein** [comment]
I also verified the tarball checksum after download.

**Comment by davidrohr** [comment]
No difference to #2 functionality-wise, closing this.

**Pull request closed without merging**
